services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
    container_name: tiktok-homepage
    ports:
      - "3001:3001"
    restart: unless-stopped
